language: java
sudo: false
install: true
addons:
  sonarqube: true
env:
  global:
    - secure: ********* # defines SONAR_TOKEN=UrDGUAquUHvm6XSTRGZBbHcXumFQ5aqxG76gxYiCQIOmeHiOlX5hYr2HALeDe5VoAoBLXPoC/qd4q517zjPfMV/9A8ftdiAPw47Ypvlrj3sIQb/PbtKKLiGvwXad4epn0lsF16M26De4Up6BMBeDzSpsUp6LRt3Oci2ZrgiXLa+4H5QsFNiEaSReGUVBkRgE0vQmGlLBhPCx9l0KeLhqaLUbqs2Rup+0yVgVhJz9jhfJUxbA6UFbnbxgIDxITZTcRPxmej3GgBbAUnUOvV8HiSpAftHSgHqon2uyAScroPhzXRq6/f2f2ygHovXGU62+Z/MwsiQDzKK64ANpBLHvVEQ4L395lX1IB99ZRidk7xZv3R4khw7OeCfDDMFIXpcWPTvcsOL5KZJKFpBYzSnKQiu+kEG3UH5xrASgjv6SOAy8KMRQsXbr9yHAenympou0/QjX73fiUdpGsC7eVb7sPQPAf18JRCCitsdrHG7Hw2Ipxq2miugOljk5mTp2vWDdcdBz2kV97NPpEonpOi3A/pV5pbEY0p2GfsOadHh0cl2ryoiOGrBNuqx4ozxs8/YAgoBtZRfFdr7rPH+b9LGUvFK+Q0jOqnYlR9+rEeb3FfC2hztSzdInF+taJDuhurYZp9dtH14fsIgmGo3GchRI6V9BHhymeIBkBIguNtaeNiQ=
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'