language: java
sudo: false
install: true
addons:
  sonarqube: true
env:
  global:
  - secure: "$SONAR_TOKEN"
  - secure: K5usKPeqtPdyHH4ynyzxeEFHkjoZQ+HhUc9wS6yxRlDLHWRPD9ku8/7YK7Lpk144Eo0dd+HHft0FMKzyCAlNWdZjeUz3boT0N2GnwT0y9xXmdB5JW5lIpU6w82iKyFDQZ58ZnOyKqTfWFuRKPTjVDoNIJg+7BtrSmBDJ//fun5abIZq61vJAnB6nDImiKiDUGr3YK7LhEpIMhJwCOT/hLXLhU9CsEsTqbTcaNKmEHlB7AbbMKaLa0p9fqBAKRTyUe7HseKHFbVxJ+wE33ROH6FjnBX509eDvnMYMH3vAJgo7vBtJLHyLRF/vJ0qlkafmRwA7GlUqiiIQpB4PvoPxGI/xH/g344yTz0VG8Lw8+WJr9KXEo/zILB69gCYuLyjFty8TvaVjyLHx05psH7+38csH8gHy0mTcxFfBGdmOlJUwAdSYbsetT0IsoS1J5ndzC9mG6y1VpzvlKCBZvJ06QQZSFPMS4ojHCqhMi4x6PCgUN2GWqre2+mADiwzl3asKag1N2LUxKW6PE7tAu+2UdMqhKFNc5akpa4MYpeyCPp1N868JwyXIrlZ5E0d+py/fjIa9fhuwYi5wrPHg8kd8kbFKXud+vEv+y/2s2jkPX59tUUtF3BvvUDiPUgAT35JZVxH6SJbJdzbyNBQ7JKCdrhi5Gb18oi87+CHXK670l50=
script:
- "./gradlew sonarqube"
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
notifications:
  slack:
    secure: aUDqFgNWtFWrO/5jCzBPzCCLMKaIQ++AOmI5MD77WYzVP6rafZX49yGDBOK18rJAV1Cc1cr8PW9rE3RNIjwPfeeUagTwMuXmSNKLTRL+JNI1qMxV5sjUox8UdLZ9JQYquSBxSSwU4NAS10yFK8W2b/oq1ocdkD//LRRTQg6K+a408tLCv7/GnJv0myh4B/wNQomsBYXXGBhIzy7RTAU5dKcTfPDkiVEdsSp1dSqsaQkw+KXK3iJxUT4yq+xk2+Da++fpdn7U9EiDoU3gLENJbMxpHaMQKftkfe2HCqoQVIqsCZtLY7mRef3/UCEinAw0CFfPPucfVPslRECaqe2oTVSMp9XrDfEBoBwtpokh5Df5BKsTLK4Yu0Disg66++XvZwyocyPhQhJPxD6krKz6K9Uwgz19Kljuo5mmWhGg4xysWc6r+6VoIj6+y0wicJ/ASNd5rKsu93rdq8KEjRMh4yGFQ4bZ0OeA2SgQHZo6e3w1qhCluqe7Way9/mYn/W+85Yqlho07YJqndhB1m+y/Y0NsN/YkR91HPFt66BlwRU2EJ21fSvHplYJ1/P81IA9EUYMTmqt21Zo+fMFmD9fJG1etUIYNWvEvD2YAH+lzpxNWHXGvFHSZJ0OnXup1GRHa+K8BTmzgw6vY8vmED+HgylBpiTlAx5EZ3JItmIkcao8=
